/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-11 03:45:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import kb.BBS;
import kb.ConnMysql;

public final class bbs_005fsample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kb.BBS");
    _jspx_imports_classes.add("kb.ConnMysql");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html class=\"no-js\" lang=\"\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>커뮤니티</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\n");
      out.write("\n");
      out.write("        <!-- all css here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/pe-icon-7-stroke.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../css/meanmenu.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/responsive.css\">\n");
      out.write("        <script src=\"../js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("        <link href=\"../styles.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t\t<!-- main-menu-area-start -->\n");
      out.write("\t\t\t<div class=\"header-top-area black-bg hidden-xs\" >\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-right\" style=\"margin-bottom:0px\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"userId\">qkr03210@gmail.com</span>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>+82 10 9774 5263</span>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"header-icon floatright\" >\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<a href=\"https://github.com/dhw1009/JspTeamproject\" ><i class=\"fa fa-github\" ></i></a> -->\n");
      out.write("\t\t\t\t\t\t\t\t");

									Object id = (String) session.getAttribute("id");
									if (id != null) {
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"color:white;\">");
      out.print(id);
      out.write("님, 환영합니다!</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"../login/logout.jsp\">Log Out</a>\n");
      out.write("                        \t\t");
}else{ 
      out.write("\n");
      out.write("                                    <a href=\"../login/signin.jsp\">Sign Up</a>\n");
      out.write("                        \t\t\t<a href=\"../login/login.jsp\">Log In</a>\n");
      out.write("                          \t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"main-menu-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../index.jsp\"><img src=\"../img/logo/1.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-menu floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"../index.jsp\">Home</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"../ViewAllFes.jsp\">festival</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"../bbs/bbs_sample.jsp\">community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"../team.html\">team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- main-menu-area-end -->\n");
      out.write("\t\t\t<!-- breadcrumb-area-start -->\n");
      out.write("\t\t\t<div class=\"breadcrumb-area bg-color ptb-100\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"breadcrumb-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h1>커뮤니티</h1>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"breadcrumb-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"../index.jsp\">home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>community</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- breadcrumb-area-end -->\n");
      out.write("\n");
      out.write("\t\t</header>\n");
      out.write("        <div class=\"container\">\n");
      out.write("\t\t<table class=\"table\">\n");
      out.write("\t\t\t<thead>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>번호</th>\n");
      out.write("\t\t\t\t\t<th width=\"700px\">제목</th>\n");
      out.write("\t\t\t\t\t<th>작성자</th>\n");
      out.write("\t\t\t\t\t<th>작성일</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</thead>\n");
      out.write("\t\t<tbody>\n");
      out.write("\n");

ConnMysql mysql = new  ConnMysql();
ArrayList<BBS> list = new ArrayList<BBS>();
list=mysql.selectBBS();
String w_id="";
String text="";
String title="";
String idx="";

for(int i=0;i<list.size();i++){
	BBS bbs = list.get(i);
	w_id=bbs.getId();
	text=bbs.getText();
	title=bbs.getTitle();
	idx=bbs.getIdx();

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr onclick=\"location.href='readbbs.jsp?id=");
      out.print(w_id);
      out.write("&text=");
      out.print(text);
      out.write("&title=");
      out.print(title);
      out.write("&idx=");
      out.print(idx);
      out.write("'\">\n");
      out.write("<th id=\"T_idx\">");
out.print(bbs.getIdx()); 
      out.write("</th>\n");
      out.write("\t<th id=\"T_title\" style=\"cursor:pointer\">");
out.print(bbs.getTitle()); 
      out.write("</th>\n");
      out.write("\t<th>");
out.print(bbs.getId()); 
      out.write("</th>\n");
      out.write("\t<th>");
out.print(bbs.getDate()); 
      out.write("</th>\n");
      out.write("</tr>\n");
}
      out.write("\n");
      out.write("\n");
      out.write("</tbody>\n");
      out.write("</table>\n");
      out.write("<div class=\"floatright text-center\">\n");
      out.write("\t\t\t\t\t\t\t");
 if(id!=null){ 
      out.write("\n");
      out.write("                    \t\t\t<a class=\"btn btn-primary btn-xl rounded-pill mt-5\" onclick=\"var windowObj = window.open('write.jsp', '', 'width=600 height=400')\" >글쓰기</a>\n");
      out.write("            \t\t\t\t");
}else{
      out.write("\n");
      out.write("                \t\t\t\t<a class=\"btn btn-primary btn-xl rounded-pill mt-5\" onclick=\"alert('로그인 하세요.')\" >글쓰기</a>\n");
      out.write("           \t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
