/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-13 14:30:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import example.Festival;
import java.util.ArrayList;
import example.Festival_DBManager;
import java.util.Calendar;

public final class festival_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("example.Festival_DBManager");
    _jspx_imports_classes.add("example.Festival");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 박상준 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

request.setCharacterEncoding("UTF-8");
String fes_name = request.getParameter("fes_name");
Festival_DBManager fdbm = new Festival_DBManager();
Festival fest=fdbm.SelectFestivalByName(fes_name);
System.out.println(fest.toString());

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>2021 대구 축제</title>\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("<!-- Place favicon.ico in the root directory -->\n");
      out.write("\n");
      out.write("<!-- all css here -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pe-icon-7-stroke.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/meanmenu.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("<script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("<!-- 박상준 -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"d3/d3.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".map_wrap, .map_wrap * {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tfont-family: 'Malgun Gothic', dotum, '돋움', sans-serif;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".map_wrap {\n");
      out.write("\twidth: 60%;\n");
      out.write("\theight: 400px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category {\n");
      out.write("\tposition: relative;\n");
      out.write("\ttop: 10px;\n");
      out.write("\tleft: 10px;\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\tborder: 1px solid #909090;\n");
      out.write("\tbox-shadow: 0 1px 1px rgba(0, 0, 0, 0.4);\n");
      out.write("\tbackground: #fff;\n");
      out.write("\toverflow: hidden;\n");
      out.write("\tz-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li {\n");
      out.write("\tfloat: left;\n");
      out.write("\tlist-style: none;\n");
      out.write("\twidth: 50px; px;\n");
      out.write("\tborder-right: 1px solid #acacac;\n");
      out.write("\tpadding: 6px 0;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li.on {\n");
      out.write("\tbackground: #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li:hover {\n");
      out.write("\tbackground: #ffe6e6;\n");
      out.write("\tborder-left: 1px solid #acacac;\n");
      out.write("\tmargin-left: -1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li:last-child {\n");
      out.write("\tmargin-right: 0;\n");
      out.write("\tborder-right: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li span {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tmargin: 0 auto 3px;\n");
      out.write("\twidth: 27px;\n");
      out.write("\theight: 28px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .category_bg {\n");
      out.write("\tbackground:\n");
      out.write("\t\turl(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_category.png)\n");
      out.write("\t\tno-repeat;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .bank {\n");
      out.write("\tbackground-position: -10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .mart {\n");
      out.write("\tbackground-position: -10px -36px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .pharmacy {\n");
      out.write("\tbackground-position: -10px -72px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .oil {\n");
      out.write("\tbackground-position: -10px -108px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .cafe {\n");
      out.write("\tbackground-position: -10px -144px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li .store {\n");
      out.write("\tbackground-position: -10px -180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#category li.on .category_bg {\n");
      out.write("\tbackground-position-x: -46px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo_wrap {\n");
      out.write("\tposition: absolute;\n");
      out.write("\tbottom: 28px;\n");
      out.write("\tleft: -150px;\n");
      out.write("\twidth: 300px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo {\n");
      out.write("\tposition: relative;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder-radius: 6px;\n");
      out.write("\tborder: 1px solid #ccc;\n");
      out.write("\tborder-bottom: 2px solid #ddd;\n");
      out.write("\tpadding-bottom: 10px;\n");
      out.write("\tbackground: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo:nth-of-type(n) {\n");
      out.write("\tborder: 0;\n");
      out.write("\tbox-shadow: 0px 1px 2px #888;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo_wrap .after {\n");
      out.write("\tcontent: '';\n");
      out.write("\tposition: relative;\n");
      out.write("\tmargin-left: -12px;\n");
      out.write("\tleft: 50%;\n");
      out.write("\twidth: 22px;\n");
      out.write("\theight: 12px;\n");
      out.write("\tbackground:\n");
      out.write("\t\turl('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo a, .placeinfo a:hover, .placeinfo a:active {\n");
      out.write("\tcolor: #fff;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo a, .placeinfo span {\n");
      out.write("\tdisplay: block;\n");
      out.write("\ttext-overflow: ellipsis;\n");
      out.write("\toverflow: hidden;\n");
      out.write("\twhite-space: nowrap;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo span {\n");
      out.write("\tmargin: 5px 5px 0 5px;\n");
      out.write("\tcursor: default;\n");
      out.write("\tfont-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo .title {\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tborder-radius: 6px 6px 0 0;\n");
      out.write("\tmargin: -1px -1px 0 -1px;\n");
      out.write("\tpadding: 10px;\n");
      out.write("\tcolor: #fff;\n");
      out.write("\tbackground: #d95050;\n");
      out.write("\tbackground: #d95050\n");
      out.write("\t\turl(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/arrow_white.png)\n");
      out.write("\t\tno-repeat right 14px center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo .tel {\n");
      out.write("\tcolor: #0f7833;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".placeinfo .jibun {\n");
      out.write("\tcolor: #999;\n");
      out.write("\tfont-size: 11px;\n");
      out.write("\tmargin-top: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_container {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_title {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 130px;\n");
      out.write("\tbackground-color: green;\n");
      out.write("\tfloat: left;\n");
      out.write("\tborder-bottom-width: thin;\n");
      out.write("\tborder-bottom-color: rgba(25, 80, 100, 0);\n");
      out.write("\tborder-bottom: solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_left_btn {\n");
      out.write("\twidth: 50%;\n");
      out.write("\theight: 700px;\n");
      out.write("\tbackground-color: red;\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_right_btn {\n");
      out.write("\twidth: 50%;\n");
      out.write("\theight: 280px;\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_list {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 150px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mycss.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!--[if lt IE 8]>\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("\t<!-- Add your site or application content here -->\n");
      out.write("\t<!-- header start -->\n");
      out.write("\t<header>\n");
      out.write("\t\t<div class=\"header-top-area black-bg hidden-xs\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-6 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t<div class=\"header-icon floatright\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://github.com/dhw1009/JspTeamproject\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t");

							Object id = (String) session.getAttribute("userID");
							if (id != null) {
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a style=\"color: white;\">");
      out.print(id);
      out.write("님, 환영합니다!</a> <a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\t\thref=\"login/logout.jsp\">Log Out</a>\n");
      out.write("\t\t\t\t\t\t\t");

							} else {
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./login/signin.jsp\">Sign Up</a> <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"./login/login.jsp\">Log In</a>\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- header end -->\n");
      out.write("\t\t<!-- main-menu-area-start -->\n");
      out.write("\t\t<div class=\"main-menu-area\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"img/logo/1.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-9 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t<div class=\"main-menu floatright\">\n");
      out.write("\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<li><a href=\"ViewAllFes.jsp\">festival</a></li> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"bbs/bbs.jsp\">community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"team.jsp\">team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- main-menu-area-end -->\n");
      out.write("\t</header>\n");
      out.write("\t<!-- header end -->\n");
      out.write("\t<!-- What-wedo-area-start -->\n");
      out.write("\t<div class=\"what-we-do-area pt-50 pb-70\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-offset-1 col-md-10\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t<h1>");
      out.print(fest.getFes_name());
      out.write("</h1>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t<img style=\"border: 20px ridge wheat\" src=\"img/festinfo/img");
      out.print(""+fest.getFes_idx());
      out.write(".jpg\"\n");
      out.write("\t\t\t\t\t\t\talt=\".\" >\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-offset-1 col-md-10\" style=\"height: 500px\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t<div id=\"map2\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: 500px; overflow: hidden;\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-offset-1 col-md-10\">\n");
      out.write("\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"category\" style=\"width: 306px; position: relative; margin:0px auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"BK9\" data-order=\"0\"><span class=\"category_bg bank\"></span>은행</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"MT1\" data-order=\"1\"><span class=\"category_bg mart\"></span>마트</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"PM9\" data-order=\"2\"><span class=\"category_bg pharmacy\"></span>숙박</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"AD5\" data-order=\"3\"><span class=\"category_bg oil\"></span>주유소</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"CE7\" data-order=\"4\"><span class=\"category_bg cafe\"></span>카페</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li id=\"CS2\" data-order=\"5\"><span class=\"category_bg store\"></span>편의점</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div  class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t<table style=\"margin:0px auto;\">\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width:150px\"><h2>축제 내용</h2></td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width:10px\"></td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-bottom: 0px;    margin-bottom: 0px;\"><h2>");
      out.print(fest.getFes_content() );
      out.write("</h2></td>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><h2>연락처</h2></td>\n");
      out.write("\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-bottom: 0px;    margin-bottom: 0px;\"><h2>");
      out.print(fest.getFes_tel());
      out.write("</h2></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><h2>홈페이지</h2></td>\n");
      out.write("\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-bottom: 0px;    margin-bottom: 0px;\"><h2>");
      out.print(fest.getFes_home());
      out.write("</h2></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><h2>주소</h2></td>\n");
      out.write("\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-bottom: 0px;    margin-bottom: 0px;\"><h2>");
      out.print(fest.getFes_addr());
      out.write("</h2></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t<!-- What-wedo-area-end -->\n");
      out.write("\t\n");
      out.write("\t<!-- footer start -->\n");
      out.write("\t<footer>\n");
      out.write("\t\t<div class=\"footer-bottom-area\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"social-icons text-center\">\n");
      out.write("\t\t\t\t\t<label>Find Us:</label> <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-github\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-tumblr\"></i></a> <a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-ge\"></i></a> <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-amazon\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-codepen\"></i></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"copyright text-center\">\n");
      out.write("\t\t\t\t\t<p>Smoth template - All rights reserved - 2018 짤 Made by</p>\n");
      out.write("\t\t\t\t\t<a href=\"#\">ThemePure</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- footer end -->\n");
      out.write("\t<!-- all js here -->\n");
      out.write("\t<script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.meanmenu.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.mixitup.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.counterup.min.js\"></script>\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\n");
      out.write("\t<script src=\"js/plugins.js\"></script>\n");
      out.write("\t<script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=6aec230d2b24b46cf01eb03868da5536&libraries=services\"></script>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\tvar placeOverlay = new kakao.maps.CustomOverlay({zIndex:1}), \n");
      out.write("\n");
      out.write("    contentNode = document.createElement('div'), \n");
      out.write("    markers = [], \n");
      out.write("    currCategory = ''; \n");
      out.write("\n");
      out.write("\t\tvar mapContainer2 = document.getElementById('map2'), mapOption2 = {\n");
      out.write("\t\t\tcenter : new kakao.maps.LatLng(\n");
      out.write("\t");
      out.print(fest.getFes_x());
      out.write("\n");
      out.write("\t\t,\n");
      out.write("\t");
      out.print(fest.getFes_y());
      out.write("\n");
      out.write("\t\t),\n");
      out.write("\t\t\tdraggable : false,\n");
      out.write("\t\t\tlevel : 5\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tvar map2 = new kakao.maps.Map(mapContainer2, mapOption2);\n");
      out.write("\n");
      out.write("\t\tvar ps = new kakao.maps.services.Places(map2);\n");
      out.write("\n");
      out.write("\t\tkakao.maps.event.addListener(map2, 'idle', searchPlaces);\n");
      out.write("\n");
      out.write("\t\tcontentNode.className = 'placeinfo_wrap';\n");
      out.write("\n");
      out.write("\t\taddEventHandle(contentNode, 'mousedown', kakao.maps.event.preventMap);\n");
      out.write("\t\taddEventHandle(contentNode, 'touchstart', kakao.maps.event.preventMap);\n");
      out.write("\n");
      out.write("\t\tplaceOverlay.setContent(contentNode);\n");
      out.write("\n");
      out.write("\t\taddCategoryClickEvent();\n");
      out.write("\n");
      out.write("\t\tfunction addEventHandle(target, type, callback) {\n");
      out.write("\t\t\tif (target.addEventListener) {\n");
      out.write("\t\t\t\ttarget.addEventListener(type, callback);\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttarget.attachEvent('on' + type, callback);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction searchPlaces() {\n");
      out.write("\t\t\tif (!currCategory) {\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tplaceOverlay.setMap(null);\n");
      out.write("\t\t\tremoveMarker();\n");
      out.write("\n");
      out.write("\t\t\tps.categorySearch(currCategory, placesSearchCB, {\n");
      out.write("\t\t\t\tuseMapBounds : true\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction placesSearchCB(data, status, pagination) {\n");
      out.write("\t\t\tif (status === kakao.maps.services.Status.OK) {\n");
      out.write("\t\t\t\tdisplayPlaces(data);\n");
      out.write("\t\t\t} else if (status === kakao.maps.services.Status.ZERO_RESULT) {\n");
      out.write("\n");
      out.write("\t\t\t} else if (status === kakao.maps.services.Status.ERROR) {\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction displayPlaces(places) {\n");
      out.write("\t\t\tvar order = document.getElementById(currCategory).getAttribute(\n");
      out.write("\t\t\t\t\t'data-order');\n");
      out.write("\n");
      out.write("\t\t\tfor (var i = 0; i < places.length; i++) {\n");
      out.write("\n");
      out.write("\t\t\t\tvar marker = addMarker(new kakao.maps.LatLng(places[i].y,\n");
      out.write("\t\t\t\t\t\tplaces[i].x), order);\n");
      out.write("\t\t\t\t(function(marker, place) {\n");
      out.write("\t\t\t\t\tkakao.maps.event.addListener(marker, 'click', function() {\n");
      out.write("\t\t\t\t\t\tdisplayPlaceInfo(place);\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t})(marker, places[i]);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction addMarker(position, order) {\n");
      out.write("\t\t\tvar imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_category.png', imageSize = new kakao.maps.Size(\n");
      out.write("\t\t\t\t\t27, 28), imgOptions = {\n");
      out.write("\t\t\t\tspriteSize : new kakao.maps.Size(72, 208),\n");
      out.write("\t\t\t\tspriteOrigin : new kakao.maps.Point(46, (order * 36)),\n");
      out.write("\t\t\t\toffset : new kakao.maps.Point(11, 28)\n");
      out.write("\t\t\t}, markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize,\n");
      out.write("\t\t\t\t\timgOptions), marker = new kakao.maps.Marker({\n");
      out.write("\t\t\t\tposition : position,\n");
      out.write("\t\t\t\timage : markerImage\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\tmarker.setMap(map2);\n");
      out.write("\t\t\tmarkers.push(marker);\n");
      out.write("\n");
      out.write("\t\t\treturn marker;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction removeMarker() {\n");
      out.write("\t\t\tfor (var i = 0; i < markers.length; i++) {\n");
      out.write("\t\t\t\tmarkers[i].setMap(null);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tmarkers = [];\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction displayPlaceInfo(place) {\n");
      out.write("\t\t\tvar content = '<div class=\"placeinfo\">'\n");
      out.write("\t\t\t\t\t+ '   <a class=\"title\" href=\"' + place.place_url + '\" target=\"_blank\" title=\"' + place.place_name + '\">'\n");
      out.write("\t\t\t\t\t+ place.place_name + '</a>';\n");
      out.write("\n");
      out.write("\t\t\tif (place.road_address_name) {\n");
      out.write("\t\t\t\tcontent += '    <span title=\"' + place.road_address_name + '\">'\n");
      out.write("\t\t\t\t\t\t+ place.road_address_name\n");
      out.write("\t\t\t\t\t\t+ '</span>'\n");
      out.write("\t\t\t\t\t\t+ '  <span class=\"jibun\" title=\"' + place.address_name + '\">(지번 : '\n");
      out.write("\t\t\t\t\t\t+ place.address_name + ')</span>';\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tcontent += '    <span title=\"' + place.address_name + '\">'\n");
      out.write("\t\t\t\t\t\t+ place.address_name + '</span>';\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tcontent += '    <span class=\"tel\">' + place.phone + '</span>'\n");
      out.write("\t\t\t\t\t+ '</div>' + '<div class=\"after\"></div>';\n");
      out.write("\n");
      out.write("\t\t\tcontentNode.innerHTML = content;\n");
      out.write("\t\t\tplaceOverlay.setPosition(new kakao.maps.LatLng(place.y, place.x));\n");
      out.write("\t\t\tplaceOverlay.setMap(map2);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction addCategoryClickEvent() {\n");
      out.write("\t\t\tvar category = document.getElementById('category'), children = category.children;\n");
      out.write("\n");
      out.write("\t\t\tfor (var i = 0; i < children.length; i++) {\n");
      out.write("\t\t\t\tchildren[i].onclick = onClickCategory;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction onClickCategory() {\n");
      out.write("\t\t\tvar id = this.id, className = this.className;\n");
      out.write("\n");
      out.write("\t\t\tplaceOverlay.setMap(null);\n");
      out.write("\n");
      out.write("\t\t\tif (className === 'on') {\n");
      out.write("\t\t\t\t//     \talert(markers.length);\n");
      out.write("\t\t\t\tcurrCategory = '';\n");
      out.write("\t\t\t\tchangeCategoryClass();\n");
      out.write("\t\t\t\tremoveMarker();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tcurrCategory = id;\n");
      out.write("\t\t\t\tchangeCategoryClass(this);\n");
      out.write("\t\t\t\tsearchPlaces();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction changeCategoryClass(el) {\n");
      out.write("\t\t\tvar category = document.getElementById('category'), children = category.children, i;\n");
      out.write("\n");
      out.write("\t\t\tfor (i = 0; i < children.length; i++) {\n");
      out.write("\t\t\t\tchildren[i].className = '';\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tif (el) {\n");
      out.write("\t\t\t\tel.className = 'on';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t//마커가 표시될 위치입니다 \n");
      out.write("\t\tvar markerPosition = new kakao.maps.LatLng(\n");
      out.write("\t");
      out.print(fest.getFes_x());
      out.write(',');
      out.print(fest.getFes_y() );
      out.write("); \n");
      out.write("\n");
      out.write("//마커를 생성합니다\n");
      out.write("var mark = new kakao.maps.Marker({\n");
      out.write("position: markerPosition\n");
      out.write("});\n");
      out.write("\n");
      out.write("mark.setMap(map2);\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
