/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-02 01:58:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import example.Festival;
import java.util.ArrayList;
import example.Festival_DBManager;
import java.util.Calendar;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("example.Festival_DBManager");
    _jspx_imports_classes.add("example.Festival");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 박상준 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- 달력용 박상준-->\r\n");

Festival_DBManager fsdb=new Festival_DBManager();
ArrayList<Festival> list = fsdb.SelectAllFestival();
ArrayList<Festival> list2;
Calendar cal = Calendar.getInstance();

int nowYear = cal.get(Calendar.YEAR);
int nowMonth = cal.get(Calendar.MONTH) + 1;//0~11월까지라 +1

String fyear = request.getParameter("year");
String fmonth = request.getParameter("month");
// String selectedFestival_s = request.getParameter("festival");
// int selectedFestival=0;
int year = nowYear;
int month = nowMonth;

if (fyear != null) {
	year = Integer.parseInt(fyear);
}

if (fmonth != null) {
	month = Integer.parseInt(fmonth);
}

// if(selectedFestival_s!=null)
// {
// 	selectedFestival=Integer.parseInt(selectedFestival_s);
// }
cal.set(year, month - 1, 1);

year = cal.get(Calendar.YEAR);
month = cal.get(Calendar.MONTH) + 1;

int endDay = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
int week = cal.get(Calendar.DAY_OF_WEEK);
if(month<10)
{
	list2 = fsdb.SelectFestivalByMonth(year+"-0"+month);
}
else
	list2 = fsdb.SelectFestivalByMonth(year+"-"+month);


//축제 일자만 나오는거 (""+fst.getFes_end()).substring(8, 10)


      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>대구축제</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.15.3/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"./styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<!-- 박상준 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"d3/d3.js\"></script>\r\n");
      out.write("    <script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <style>\r\n");
      out.write("\t\ttable{\r\n");
      out.write("\t\t    border-spacing: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("        td{\r\n");
      out.write("        \tpadding:0px;\r\n");
      out.write("            width:120px;\r\n");
      out.write("            height:120px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("<!-- 박상준 달력 클릭하면 팝업-->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$('document').ready(function(){\r\n");
      out.write("\t\t$(\"#myTable td\").click(function(){\r\n");
      out.write("// \t\t\tvar tdArray = new Array();\r\n");
      out.write("\t\t\tvar value = $(this).text();\r\n");
      out.write("\t\t\tvar dstyle=$(this).find(\"div\").css(\"background-color\");\r\n");
      out.write("\t\t\tvar dhtml = $(this).css(\"background-color\");\r\n");
      out.write("\t\t\tif(value>0){\r\n");
      out.write("// \t\t\t\tTODO 일단 팝업에 축제정보 뜨는것까지\r\n");
      out.write("\t\t\t\tpopup=window.open(\"SelectedDay.jsp?day=\"+value+\"&month=\"+");
      out.print(month);
      out.write("+\"&year=\"+");
      out.print(year);
      out.write(", \"ppu\", \"width=300, height=500, left=500, top=50\");\t\t    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("var index=0;\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\tslideShow();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function slideShow(){\r\n");
      out.write("\tvar i;\r\n");
      out.write("\tvar x=document.getElementsByClassName(\"slide\");\r\n");
      out.write("\tfor(i=0;i<x.length; i++){\r\n");
      out.write("\t\tx[i].style.display=\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\tindex++;\r\n");
      out.write("\tif(index>x.length){\r\n");
      out.write("\t\tindex=1;\r\n");
      out.write("\t}\r\n");
      out.write("\tx[index-1].style.display=\"block\";\r\n");
      out.write("\tsetTimeout(slideShow,3000);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"home.jsp\">대구축제</a>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"./bbs/bbs.jsp\">커뮤니티</a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                         \t");

							Object id = (String) session.getAttribute("id");
							if (id != null) {
							
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\" style=\"color:white;\">");
      out.print(id);
      out.write("님, 환영합니다!</li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"./login/login.jsp\" onclick=\"location.href='./login/logout.jsp'\">Log Out</a></li>\r\n");
      out.write("\r\n");
      out.write("                        ");
}else{ 
      out.write("\r\n");
      out.write("                                                  <li class=\"nav-item\"><a class=\"nav-link\" href=\"./login/signin.jsp\">Sign Up</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"./login/login.jsp\">Log In</a></li>\r\n");
      out.write("                          ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <header class=\"masthead text-center text-white\">\r\n");
      out.write("            <div class=\"masthead-content\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <h1 class=\"masthead-heading mb-0\">2021 대구축제 </h1>\r\n");
      out.write("                    <h2 class=\"masthead-subheading mb-0\">대굴대굴</h2>\r\n");
      out.write("               \r\n");
      out.write("                    <br> <br>\r\n");
      out.write("                    ");
 int a; 
      out.write("\r\n");
      out.write("                    <a href=\"festival.jsp?a=1\"><img class=\"slide\" alt=\"\" src=\"./img/축제1.jpg\" width=1200px height=500px align=\"center\"></a>\r\n");
      out.write("<a href=\"festival.jsp?a=2\"><img class=\"slide\" alt=\"\" src=\"./img/축제2.jpg\" width=1200px height=500px align=\"center\"></a>\r\n");
      out.write("<a href=\"festival.jsp\"><img class=\"slide\" alt=\"\" src=\"./img/축제3.jpg\" width=1200px height=500px align=\"center\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bg-circle-1 bg-circle\"></div>\r\n");
      out.write("            <div class=\"bg-circle-2 bg-circle\"></div>\r\n");
      out.write("            <div class=\"bg-circle-3 bg-circle\"></div>\r\n");
      out.write("            <div class=\"bg-circle-4 bg-circle\"></div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:center\">\r\n");
      out.write("    <div>\r\n");
      out.write("<!--         <a href=\"chart/chart1.jsp\">chart1</a> -->\r\n");
      out.write("        <a href = \"home.jsp?year=");
      out.print(year );
      out.write("&month=");
      out.print(month -1 );
      out.write("\">이전달</a>&nbsp;\r\n");
      out.write("        <b>");
      out.print(year);
      out.write("년&nbsp;&nbsp;");
      out.print(month);
      out.write("월</b>\r\n");
      out.write("\t\t<a href = \"home.jsp?year=");
      out.print(year );
      out.write("&month=");
      out.print(month +1 );
      out.write("\">&nbsp;다음달</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t");

    		int listCount=list2.size();
    	
    		if(listCount>5)
    		{
    			listCount=5;
    		}
    		//TODO 지울거
    		for(int i = 0;i<listCount;i++){
    			Festival fes=list2.get(i);
    	
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("    \t\t<a href = \"#\">");
      out.print(fes.getFes_name());
      out.write('/');
      out.write('/');
      out.print(fes.getFes_start());
      out.write('/');
      out.write('/');
      out.print(fes.getFes_end());
      out.write("</a><br>\r\n");
      out.write("    \t");

    		}
    	
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<!-- <a href=\"\"></a> -->\r\n");
      out.write("\t\t<table border=\"1\" id=\"myTable\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"color: red;\">일</td>\r\n");
      out.write("\t\t\t\t<td>월</td>\r\n");
      out.write("\t\t\t\t<td>화</td>\r\n");
      out.write("\t\t\t\t<td>수</td>\r\n");
      out.write("\t\t\t\t<td>목</td>\r\n");
      out.write("\t\t\t\t<td>금</td>\r\n");
      out.write("\t\t\t\t<td style=\"color: blue\">토</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

				for (int i = 1; i < week; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \t\t\t끝나는 날까지 for문을 통해서 숫자를 출력한 것이다. week는 1일 제외하고 계산된다. -->\r\n");
      out.write("\t\t\t\t");

				for (int j = 1; j <= endDay; j++) {
					week++;
					if (week % 7 == 2) {
				
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

				}
				if (week % 7 == 2) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"color: red\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

				} else if (week % 7 == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"color: blue\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

				} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"color: black\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

				}

				}
				
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \t<script type=\"text/javascript\"> \r\n");
      out.write("\t\t\tfunction addBar(day) { \r\n");
      out.write("\t\t          // Enter\r\n");
      out.write("\t\t   \t\t");
for(int i =0;i<listCount;i++){
      out.write("\r\n");
      out.write("\t            \td3.select(day) // <-\r\n");
      out.write("\t                \t.append(\"div\") // <- F\r\n");
      out.write("\t                      \t.attr(\"class\", \"h-bar");
      out.print(i);
      out.write("\")\r\n");
      out.write("\t                \t.append(\"span\"); // <- G\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 for(int i =1;i<=endDay;i++){
      out.write("\r\n");
      out.write("\t\t\t\taddBar(\"");
      out.print("#day"+i);
      out.write("\");\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			int start=0;
			int finish=0;
			
			if(list2.size()!=0)
			{
				int k;
				for( k= 0; k<listCount;k++){
					start=0;
					finish=0;
				
					Festival fst= list2.get(k);
					
					start=Integer.parseInt((""+fst.getFes_start()).substring(8, 10));

					finish=Integer.parseInt((""+fst.getFes_end()).substring(8, 10));
					
					if(Integer.parseInt((""+fst.getFes_start()).substring(5, 7))!=month)
					{//축제 시작일(day)이 끝나는날(day)보다 많으면 이전달임
						//FIXME 생각해보니 시작일 4/19 종료일 5/20이면 19~20으로 계산될듯 비교를 월로 해야할듯
						start=1;
					}
					if(Integer.parseInt((""+fst.getFes_end()).substring(5, 7))!=month)
					{
						finish=endDay;
					}
					
					for(int i =start;i<=finish;i++){
						String[] calColor=new String[5];
						calColor[0]="yellow";
						calColor[1]="orange";
						calColor[2]="red";
						calColor[3]="#c7ed9c";
						calColor[4]="#abf3ee";
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\td3.select(\"");
      out.print("#day"+i);
      out.write("\")\r\n");
      out.write("\t\t\t\t\t\t\t.select(\"div.");
      out.print("h-bar"+k);
      out.write("\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.style(\"background-color\",\"");
      out.print(calColor[k]);
      out.write("\")\r\n");
      out.write("\t\t\t\t\t");
}
				 }
			}
      out.write("\r\n");
      out.write("    </script> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
