/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-14 02:11:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import example.Festival;
import java.util.ArrayList;
import example.Festival_DBManager;
import java.util.Calendar;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("example.Festival_DBManager");
    _jspx_imports_classes.add("example.Festival");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 박상준 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!-- 달력용 박상준-->\n");

Festival_DBManager fsdb=new Festival_DBManager();
ArrayList<Festival> list = fsdb.SelectAllFestival();
ArrayList<Festival> list2;
Calendar cal = Calendar.getInstance();

int nowYear = cal.get(Calendar.YEAR);
int nowMonth = cal.get(Calendar.MONTH) + 1;//0~11월까지라 +1

String fyear = request.getParameter("year");
String fmonth = request.getParameter("month");
// String selectedFestival_s = request.getParameter("festival");
// int selectedFestival=0;
int year = nowYear;
int month = nowMonth;

if (fyear != null) {
	year = Integer.parseInt(fyear);
}

if (fmonth != null) {
	month = Integer.parseInt(fmonth);
}

// if(selectedFestival_s!=null)
// {
// 	selectedFestival=Integer.parseInt(selectedFestival_s);
// }
cal.set(year, month - 1, 1);

year = cal.get(Calendar.YEAR);
month = cal.get(Calendar.MONTH) + 1;

int endDay = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
int week = cal.get(Calendar.DAY_OF_WEEK);
if(month<10)
{
	list2 = fsdb.SelectFestivalByMonth(year+"-0"+month);
}
else
	list2 = fsdb.SelectFestivalByMonth(year+"-"+month);


//축제 일자만 나오는거 (""+fst.getFes_end()).substring(8, 10)


      out.write("\n");
      out.write("<!-- 로그인용 -->\n");



      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>2021 대구 축제 </title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- all css here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/pe-icon-7-stroke.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/meanmenu.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("        <script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("        <!-- 박상준 -->\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\"/>\n");
      out.write("    \t<script type=\"text/javascript\" src=\"d3/d3.js\"></script>\n");
      out.write("    \t<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("        \t<style>\n");
      out.write("\t\t\t\ttable{\n");
      out.write("\t\t    \t\tborder-spacing: 0px;\n");
      out.write("\t\t\t\t}\n");
      out.write("        \t\ttd{\n");
      out.write("        \t\t\tpadding:0px;\n");
      out.write("            \t\twidth:120px;\n");
      out.write("            \t\theight:120px;\n");
      out.write("        \t\t}\n");
      out.write("    \t\t</style>\n");
      out.write("\t\t<!-- 박상준 달력 클릭하면 팝업-->\n");
      out.write("    \t<script type=\"text/javascript\">\n");
      out.write("\t\t$('document').ready(function(){\n");
      out.write("\t\t\t$(\"#myTable td\").click(function(){\n");
      out.write("\t\t\t\tvar value = $(this).text();\n");
      out.write("\t\t\t\tif(value>0){\n");
      out.write("\t\t\t\t\t//년 월 일 넘겨줌\n");
      out.write("\t\t\t\t\tpopup=window.open(\"SelectedDay.jsp?day=\"+value+\"&month=\"+");
      out.print(month);
      out.write("+\"&year=\"+");
      out.print(year);
      out.write(", \"ppu\", \"width=300, height=500, left=500, top=50\");\t\t    \n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t})\n");
      out.write("\t\t</script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!--[if lt IE 8]>\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("        <!-- Add your site or application content here -->\n");
      out.write("\t\t<!-- header start -->\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<div class=\"header-top-area black-bg hidden-xs\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\n");
      out.write("<!-- \t\t\t\t\t\t\t<ul class=\"top-right\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<span id=\"userId\">qkr03210@gmail.com</span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<span>+82 10 9774 5263</span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t</ul> -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"header-icon floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://github.com/dhw1009/JspTeamproject\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t");

									Object id = (String) session.getAttribute("userID");
									if (id != null) {
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"color:white;\">");
      out.print(id);
      out.write("님, 환영합니다!</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"login/logoutAction.jsp\">Log Out</a>\n");
      out.write("                        \t\t");
}else{ 
      out.write("\n");
      out.write("                                    <a href=\"./login/signin.jsp\">Sign Up</a>\n");
      out.write("                        \t\t\t<a href=\"./login/login.jsp\">Log In</a>\n");
      out.write("                          \t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- header end -->\n");
      out.write("\t\t\t<!-- main-menu-area-start -->\n");
      out.write("\t\t\t<div class=\"main-menu-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"img/logo/1.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-menu floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"bbs/bbs.jsp\">community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"team.jsp\">team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- main-menu-area-end -->\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- header end -->\n");
      out.write("\t\t<!-- slider-area-start -->\n");
      out.write("\t\t\t\t<div class=\"slider-area\">\n");
      out.write("\t\t\t<div class=\"slider-active owl-carousel\">\n");
      out.write("\t\t\t\t<div class=\"single-slider ptb-150 bg-opacity\" style=\"background-image:url(img/slider/2.jpg)\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"slider-text\">\n");
      out.write("\t\t\t\t\t\t\t<h1>신천음악버스킹<br>2021-07-06(화) ~ 14(수)</h1>\n");
      out.write("\t\t\t\t\t\t\t<p>시간・공간・세대를 초월한 다양한 뮤직과 모든 문화장르를 아우른 버스킹 <br>  다양한 음악 장르를 아우른 버스킹, 아이스이벤트, 체험부스</p>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"active\" href=\"festival.jsp?fes_name=신천 음악버스킹\">바로 가기</a>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"single-slider ptb-150 bg-opacity\" style=\"background-image:url(img/slider/3.jpg)\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"slider-text\">\n");
      out.write("\t\t\t\t\t\t\t<h1>대구국제바디페인팅페스티벌 <br>  2021-08-01(일) ~ 07(토)</h1>\n");
      out.write("\t\t\t\t\t\t\t<p>세계 정상급 아티스트들이 보여주는 색채예술의 극치!\n");
      out.write("\t\t\t\t\t\t\t<br>페인팅을 체험할 수 있는 다양한 체험 프로그램까지!</p>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"active\" href=\"festival.jsp?fes_name=대구국제바디페인팅페스티벌\">바로 가기</a>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"single-slider ptb-150 bg-opacity\" style=\"background-image:url(img/slider/1.jpg)\">\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"slider-text\">\n");
      out.write("\t\t\t\t\t\t\t<h1>치맥 페스티벌 <br>  2021-07-01(목) ~ 09(금)</h1>\n");
      out.write("\t\t\t\t\t\t\t<p>대한민국 치킨산업의 중심 대구! <br> </p>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"active\" href=\"festival.jsp?fes_name=대구치맥페스티벌\">바로 가기</a>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- slider-area-end -->\n");
      out.write("\t\t<!-- What-wedo-area-start -->\n");
      out.write("\t\t<div class=\"what-we-do-area pt-100 pb-70\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-offset-1 col-md-10\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2>축제 달력</h2>\n");
      out.write("\t\t\t\t\t\t\t\t    <div>\n");
      out.write("        <a href = \"index.jsp?year=");
      out.print(year );
      out.write("&month=");
      out.print(month -1 );
      out.write("\">이전달</a>&nbsp;\n");
      out.write("        <b>");
      out.print(year);
      out.write("년&nbsp;&nbsp;");
      out.print(month);
      out.write("월</b>\n");
      out.write("\t\t<a href = \"index.jsp?year=");
      out.print(year );
      out.write("&month=");
      out.print(month +1 );
      out.write("\">&nbsp;다음달</a>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("    \t");

    		int listCount=list2.size();
    		if(listCount>5)
    		{
    			listCount=5;
    		}
    	
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\t\t<table border=\"1\" id=\"myTable\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"color: red;\">일</td>\n");
      out.write("\t\t\t\t<td>월</td>\n");
      out.write("\t\t\t\t<td>화</td>\n");
      out.write("\t\t\t\t<td>수</td>\n");
      out.write("\t\t\t\t<td>목</td>\n");
      out.write("\t\t\t\t<td>금</td>\n");
      out.write("\t\t\t\t<td style=\"color: blue\">토</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t");

				for (int i = 1; i < week; i++) {
				
      out.write("\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\n");
      out.write("\t\t\t\t<!-- \t\t\t끝나는 날까지 for문을 통해서 숫자를 출력한 것이다. week는 1일 제외하고 계산된다. -->\n");
      out.write("\t\t\t\t");

				for (int j = 1; j <= endDay; j++) {
					week++;
					if (week % 7 == 2) {
				
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t");

				}
				if (week % 7 == 2) {
				
      out.write("\n");
      out.write("\t\t\t\t<td style=\"color: red\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\n");
      out.write("\t\t\t\t");

				} else if (week % 7 == 1) {
				
      out.write("\n");
      out.write("\t\t\t\t<td style=\"color: blue\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\n");
      out.write("\t\t\t\t");

				} else {
				
      out.write("\n");
      out.write("\t\t\t\t<td style=\"color: black\" id=\"day");
      out.print(j);
      out.write('"');
      out.write('>');
      out.print(j);
      out.write("</td>\n");
      out.write("\t\t\t\t");

				}

				}
				
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("  \t<script type=\"text/javascript\"> \n");
      out.write("\t\t\tfunction addBar(day) { \n");
      out.write("\t\t          // Enter\n");
      out.write("\t\t   \t\t");
for(int i =0;i<listCount;i++){
      out.write("\n");
      out.write("\t            \td3.select(day) // <-\n");
      out.write("\t                \t.append(\"div\") // <- F\n");
      out.write("\t                      \t.attr(\"class\", \"h-bar");
      out.print(i);
      out.write("\")\n");
      out.write("\t                \t.append(\"span\"); // <- G\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 for(int i =1;i<=endDay;i++){
      out.write("\n");
      out.write("\t\t\t\taddBar(\"");
      out.print("#day"+i);
      out.write("\");\n");
      out.write("\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");

			int start=0;
			int finish=0;
			
			if(list2.size()!=0)
			{
				int k;
				for( k= 0; k<listCount;k++){
					start=0;
					finish=0;
				
					Festival fst= list2.get(k);
					start=Integer.parseInt((""+fst.getFes_start()).substring(8, 10));	
					finish=Integer.parseInt((""+fst.getFes_end()).substring(8, 10));
					
					if(Integer.parseInt((""+fst.getFes_start()).substring(5, 7))!=month)
					{	//축제 시작일(day)이 끝나는날(day)보다 많으면 이전달임
						//FIXME 생각해보니 시작일 4/19 종료일 5/20이면 19~20으로 계산될듯 비교를 월로 해야할듯
						start=1;
					}
					if(Integer.parseInt((""+fst.getFes_end()).substring(5, 7))!=month)
					{
						finish=endDay;
					}
					String[] calColor=new String[5];
					calColor[0]="yellow";calColor[1]="orange";calColor[2]="red";calColor[3]="#c7ed9c";calColor[4]="#abf3ee";
					for(int i =start;i<=finish;i++){
						
      out.write("\n");
      out.write("\t\t\t\t\t\td3.select(\"");
      out.print("#day"+i);
      out.write("\")\n");
      out.write("\t\t\t\t\t\t\t.select(\"div.");
      out.print("h-bar"+k);
      out.write("\")\n");
      out.write("\t\t\t\t\t\t\t\t.style(\"background-color\",\"");
      out.print(calColor[k]);
      out.write("\")\n");
      out.write("\t\t\t\t\t");

					}
				 }
			}
      out.write("\n");
      out.write("    </script> \n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<table>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t<!-- What-wedo-area-end -->\n");
      out.write("\n");
      out.write("\t\t<!-- footer start -->\n");
      out.write("\t\t<footer>\n");
      out.write("\t\t\t<div class=\"footer-bottom-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"social-icons text-center\">\n");
      out.write("\t\t\t\t\t\t<label>Find Us:</label>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-tumblr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-ge\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-amazon\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-codepen\"></i></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center\">\n");
      out.write("\t\t\t\t\t\t<p>대굴대굴 - 축제 소개 페이지 - 2021 Made by</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">박상준,신용원,김두희</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- footer end -->\n");
      out.write("\t\t<!-- all js here -->\n");
      out.write("        <script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.meanmenu.js\"></script>\n");
      out.write("        <script src=\"js/jquery.mixitup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.counterup.min.js\"></script>\n");
      out.write("        <script src=\"js/waypoints.min.js\"></script>\n");
      out.write("        <script src=\"js/plugins.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
