/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-14 02:16:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class team_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Smoth | Corporate HTML Template</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\n");
      out.write("\n");
      out.write("        <!-- all css here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/pe-icon-7-stroke.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/meanmenu.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("        <script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("    <body>\n");
      out.write("        <!--[if lt IE 8]>\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("\t\t<!-- header start -->\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<div class=\"header-top-area black-bg hidden-xs\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\n");
      out.write("<!-- \t\t\t\t\t\t\t<ul class=\"top-right\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<span id=\"userId\">qkr03210@gmail.com</span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<span>+82 10 9774 5263</span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t</ul> -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"header-icon floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"https://github.com/dhw1009/JspTeamproject\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t");

									Object id = (String) session.getAttribute("userID");
									if (id != null) {
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"color:white;\">");
      out.print(id);
      out.write("님, 환영합니다!</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"login/logout.jsp\">Log Out</a>\n");
      out.write("                        \t\t");
}else{ 
      out.write("\n");
      out.write("                                    <a href=\"./login/signin.jsp\">Sign Up</a>\n");
      out.write("                        \t\t\t<a href=\"./login/login.jsp\">Log In</a>\n");
      out.write("                          \t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- header end -->\n");
      out.write("\t\t\t<!-- main-menu-area-start -->\n");
      out.write("\t\t\t<div class=\"main-menu-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"img/logo/1.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-menu floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"bbs/bbs.jsp\">community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"team.jsp\">team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- main-menu-area-end -->\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- breadcrumb-area-start -->\n");
      out.write("\t\t<div class=\"breadcrumb-area bg-color ptb-100\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"breadcrumb-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t<h1>team</h1>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"breadcrumb-menu\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"index.jsp\">home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>team</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- breadcrumb-area-end --> \n");
      out.write("\t\t<!-- team-area-start -->\n");
      out.write("\t\t<div class=\"team-area pt-100 pb-70\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<!--공백 -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-2\"></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-team mb-30\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/team/1.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-social\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://github.com/kimduhee7524\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-inner text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6>김두희</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span>Programmer</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--공백 -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1 col-sm-1\"></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-team mb-30\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/team/2.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-social\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://github.com/qkr03210\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-inner text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6>박상준</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span>Programmer</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--공백 -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1 col-sm-1\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"single-team mb-30\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/team/3.PNG\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-social\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://github.com/sinyong1\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-inner text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6>신용원</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span>Programmer</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--공백 -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1 col-sm-1\"></div>\n");
      out.write("\t\t\t\t</div>\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- testimonial-area-start -->\n");
      out.write("\t\t<div class=\"testimonial-area ptb-80 gray-bg\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-offset-3 col-md-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t<h2>개발 후기</h2>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"testimonial-active owl-carousel\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimonial-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-img text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/testimonial/1_60.jpg\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-info text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>회원가입 페이지에서 중복체크 비밀번호 확인등 여러가지 기능들을 활용하여 편리하게 가입할 수 있도록 만들었다.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>김두희</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimonial-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-img text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/testimonial/2_60.jpg\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-info text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>이번 프로젝트를 진행하면서 jsp 화면간 값의 전달과 화면의 이동에 대해 많은 공부를 할수있었습니다.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>박상준</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testimonial-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-img text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/testimonial/3_60.PNG\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testimonial-info text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>공공데이터를 활용하여</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>신용원</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- testimonial-area-end -->\t\t\n");
      out.write("\t\t<!-- footer start -->\n");
      out.write("\t\t<footer>\n");
      out.write("\t\t\t<div class=\"footer-bottom-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"social-icons text-center\">\n");
      out.write("\t\t\t\t\t\t<label>Find Us:</label>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-tumblr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-ge\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-amazon\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-codepen\"></i></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center\">\n");
      out.write("\t\t\t\t\t\t<p>대굴대굴 - 축제 소개 페이지 - 2021 Made by</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">박상준,신용원,김두희</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- footer end -->\n");
      out.write("\t\t<!-- all js here -->\n");
      out.write("        <script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.meanmenu.js\"></script>\n");
      out.write("        <script src=\"js/jquery.mixitup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.counterup.min.js\"></script>\n");
      out.write("        <script src=\"js/waypoints.min.js\"></script>\n");
      out.write("        <script src=\"js/plugins.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
