/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-11 06:53:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ViewAllFes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Smoth | Corporate HTML Template</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\n");
      out.write("\n");
      out.write("        <!-- all css here -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/pe-icon-7-stroke.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/meanmenu.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("        <script src=\"js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!--[if lt IE 8]>\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("\t\t<!-- header start -->\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<div class=\"header-top-area black-bg hidden-xs\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"top-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Support@mail.com</span>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>+01 1800 453 7678</span>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 hidden-xs\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"header-icon floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- main-menu-area-start -->\n");
      out.write("\t\t\t<div class=\"main-menu-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\"><img src=\"img/logo/1.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-9 col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-menu floatright\">\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"ViewAllFes.jsp\">festival</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"bbs/bbs_sample.jsp\">community</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"team.jsp\">team</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mobile-menu-area\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- main-menu-area-end -->\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- header end -->\n");
      out.write("\t\t<!-- breadcrumb-area-start -->\n");
      out.write("\t\t<div class=\"breadcrumb-area bg-color ptb-100\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"breadcrumb-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t<h1>festival</h1>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"breadcrumb-menu\">\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"index.jsp\">home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>festival</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- breadcrumb-area-end -->\n");
      out.write("\t\t<div class=\"team-area pt-100 pb-70\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-offset-1 col-md-10\" style=\"height: 500px\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title text-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"red box\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- footer start -->\n");
      out.write("\t\t<footer>\n");
      out.write("\t\t\t<div class=\"footer-area black-bg ptb-80\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-widget md-30\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/logo/2.png\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"footer-address\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>We create themes and templates with bootstrap framework.</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"address\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled contact\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><p><strong><i class=\"fa fa-map-marker\"></i> </strong> vaisahali, jaipur, 302012</p></li> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><p><strong><i class=\"fa fa-envelope\"></i></strong> <a href=\"#\">Support@domain.com</a></p></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li> <p><strong><i class=\"fa fa-phone\"></i></strong> +91 1800 2345 2132</p></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li> <p><strong><i class=\"fa fa-print\"></i> </strong> 1800 2345 2132</p></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li> <p><strong><i class=\"fa fa-skype\"></i> </strong> jondoe001</p></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget mb-30\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Popular Posts</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"posts-list\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/footer/1.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5><a href=\"#\">Dolores labore quod.</a></h5>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Jan 08, 2016</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/footer/2.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5><a href=\"#\">Dolores labore ipsum quod.</a></h5>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Jan 08, 2018</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"list-img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/footer/3.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5><a href=\"#\">Dolores labore ipsum</a></h5>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Jan 01, 2016</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-4 hidden-sm\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget mb-30\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Tagcloud</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tagcloud\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Design</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Develop</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Seo</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">jQuery</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Wordpress</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Angular</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Node</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Express</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Gulp</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Sass</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Bootstrap</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Html5</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Css3</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Node</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Retina</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Sprites</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Html5</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-4\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget \">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Latest Work</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"rows\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"Flickr-list\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-1.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-2.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-3.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-4.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-5.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-6.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-7.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-8.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/portfolio/img-9.jpg\" alt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"footer-bottom-area\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"social-icons text-center\">\n");
      out.write("\t\t\t\t\t\t<label>Find Us:</label>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-tumblr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-flickr\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-github\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-ge\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-amazon\"></i></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-codepen\"></i></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center\">\n");
      out.write("\t\t\t\t\t\t<p>Smoth template - All rights reserved - 2018 ÃÂ© Made by</p>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">ThemePure</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- footer end -->\n");
      out.write("\t\t<!-- all js here -->\n");
      out.write("        <script src=\"js/vendor/jquery-1.12.0.min.js\"></script>\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.meanmenu.js\"></script>\n");
      out.write("        <script src=\"js/jquery.mixitup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.counterup.min.js\"></script>\n");
      out.write("        <script src=\"js/waypoints.min.js\"></script>\n");
      out.write("        <script src=\"js/plugins.js\"></script>\n");
      out.write("        <script src=\"js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
